name: georoute
services:

  frontend:
    image: georoute-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - georoute

  backend:
    image: georoute-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    networks:
      - georoute

  postgres:
    image: pgrouting/pgrouting:latest
    container_name: georoute_postgres
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=128MB"
    env_file:
      - backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - georoute
  
  osm-routing-import:
    image: iboates/osm2pgsql:latest
    volumes:
      - ./data/region.osm.pbf:/data/region.osm.pbf
    env_file:
      - ./backend/.env
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
    command: osm2pgsql --slim --hstore -d routing_db -H postgres -U ezmapsuser /data/region.osm.pbf
    depends_on:
      - postgres
    profiles:
      - routing-import
    networks:
      - georoute
      
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - georoute


volumes:
  postgres-data:
  redis-data:
  osm-data:
networks:
  georoute:
